services:
  pia-wireproxy:
    restart: unless-stopped
    build:
      context: .
    ports:
      - "26000-26002:26000-26002"
      - "27000-27002:27000-27002"
    environment:
      - PIA_USER=CHANGEME
      - PIA_PASS=CHANGEME
      # must be valid pia server locations
      - PIA_LOCS=NL,FR,US
      # ports are mapped to locations in the same list order
      - PROXY_SOCKS_PORTS=26000,26001,26002
      - PROXY_HTTP_PORTS=27000,27001,27002
      # credentials for both socks5 and http proxies
      - PROXY_USER=socks
      - PROXY_PASS=s0ck5
      # for internal use only, but it must not overlap with proxy ports
      # you must reserve as many ports as there are locations
      - HEALTH_PORTS=2000,2001,2002
      # time to sleep between healthcheck requests
      - HEALTH_SLEEP=10
      # ip address to use for healthcheck
      - HEALTH_IP=8.8.8.8
