services:
  pia-wireproxy:
    restart: unless-stopped
    build:
      context: .
    ports:
      - "26000-26002:26000-26002"
    environment:
      - PIA_USER=CHANGEME
      - PIA_PASS=CHANGEME
      - PIA_LOCS=NL,FR,US
      - PIA_PORT_START=26000
      - SOCKS_USER=socks
      - SOCKS_PASS=s0ck5
      - HEALTH_SLEEP=10
      - HEALTH_IP=8.8.8.8
